version: "3.8"
services:
  react-app:
    build:
      context: .

    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
